global proc shelf_bluepepper_dev () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Execute sandbox (for devs only)" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "Sandbox" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -imageOverlayLabel "Dev" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "software_python.png" 
        -image1 "software_python.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "from bluepepper import reload_bluepepper_modules\nreload_bluepepper_modules()\n\nfrom bluepepper.softwares.maya.sandbox import main\nmain()" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;

} 
